# Generated by Django 4.0.6 on 2025-01-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organization_show_zero_ledgers'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='arrival_time',
            field=models.TimeField(null=True),
        ),
    ]
