# Generated by Django 4.0.6 on 2025-01-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_organization_arrival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='clock_out_time',
            field=models.TimeField(null=True),
        ),
    ]
