# Generated by Django 4.0.6 on 2025-01-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_organization_clock_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='noOfpaidleavesallowed',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=10),
        ),
    ]
