# Generated by Django 4.0.6 on 2024-08-23 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organization_show_zero_ledgers'),
        ('product', '0010_product_minimum_stock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemreconcilationapiitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemreconcilationapiitem',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.terminal'),
        ),
        migrations.AlterUniqueTogether(
            name='itemreconcilationapiitem',
            unique_together={('branch', 'product', 'date', 'terminal')},
        ),
    ]
