# Generated by Django 4.0.6 on 2024-06-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_alter_tablreturnentry_notaxsales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='mobile-payment-type/icons/')),
                ('qr', models.ImageField(blank=True, null=True, upload_to='mobile-payment-type/qr/')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
