# Generated by Django 4.0.6 on 2024-06-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_mobilepaymentsummary_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_end_day',
            field=models.BooleanField(default=False),
        ),
    ]
