# Generated by Django 4.0.6 on 2025-01-14 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0007_organization_show_zero_ledgers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('hiring_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('marital_status', models.CharField(max_length=100, null=True)),
                ('current_status', models.CharField(max_length=100, null=True)),
                ('level', models.CharField(max_length=100, null=True)),
                ('termination_date', models.DateField(null=True)),
                ('shift', models.CharField(max_length=50, null=True)),
                ('attendance_required', models.BooleanField(null=True)),
                ('lateattendance_alert', models.BooleanField(null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='employee/images/')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.branch')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
