# Generated by Django 4.0.6 on 2025-01-17 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_dailyattendance_total_time_pay_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblcompanypaidleavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('noOfdays', models.DecimalField(decimal_places=2, default=2.5, max_digits=10)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tblpaidleaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('no_of_leaves', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tblleaveapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('applyDate', models.DateField(null=True)),
                ('noOfDays', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('noOfPaidLeaves', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('noOfUnPaidLeaves', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leaveDateFrom', models.DateField(null=True)),
                ('leaveDateTo', models.DateField(null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('current_status', models.CharField(blank=True, max_length=200, null=True)),
                ('empID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
