# Generated by Django 4.0.6 on 2025-01-17 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_tblcompanypaidleavepolicy_tblpaidleaves_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblEmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('total_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('non_taxable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emp_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
