# Generated by Django 4.0.6 on 2025-01-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_tblemployeesalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
    ]
