# Generated by Django 4.0.6 on 2025-01-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_tbldeduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblleaveapply',
            name='nepali_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tblleaveapply',
            name='nepali_month',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tblleaveapply',
            name='nepali_year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
