# Generated by Django 4.0.6 on 2025-01-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_tblleaveapply_nepali_date_tblleaveapply_nepali_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
