# Generated by Django 4.0.6 on 2025-01-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='late_attendance_flag',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='no_show_flag',
            field=models.BooleanField(null=True),
        ),
    ]
