# Generated by Django 4.0.6 on 2025-01-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_dailyattendance_late_attendance_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblleaveapply',
            name='noOfPaidLeaves_taken',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
