# Generated by Django 4.0.6 on 2024-07-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchase_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contact',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
