# Generated by Django 4.0.6 on 2025-02-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_vendor_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='grn',
            field=models.IntegerField(null=True),
        ),
    ]
