# Generated by Django 4.0.6 on 2025-02-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_purchase_grn'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpurchaseentry',
            name='grn',
            field=models.IntegerField(null=True),
        ),
    ]
