# Generated by Django 4.0.6 on 2025-01-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_remove_monthlysalaryreport_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalaryreport',
            name='fiscal_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monthlysalaryreport',
            name='month',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monthlysalaryreport',
            name='nepali_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monthlysalaryreport',
            name='nepali_year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
