# Generated by Django 4.0.6 on 2024-08-02 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_tblcrjournalentry_paidfrom_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumulativeledger',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.accountledger'),
        ),
    ]
