# Generated by Django 4.0.6 on 2024-08-13 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_accountledger_opening_count_cumulativeledger_journal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='credit_sub_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_sub_ledger', to='accounting.accountsubledger'),
        ),
        migrations.AddField(
            model_name='expense',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.tbljournalentry'),
        ),
        migrations.AlterField(
            model_name='accountledger',
            name='account_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accountchart'),
        ),
        migrations.AlterField(
            model_name='accountsubledger',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.accountledger'),
        ),
    ]
