# Generated by Django 4.0.6 on 2024-11-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_expense_credit_sub_ledger_expense_journal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=100)),
                ('bill', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tbljournalentry',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbljournalentry',
            name='narration',
            field=models.CharField(blank=True, default='-', max_length=300, null=True),
        ),
    ]
