# Generated by Django 4.0.6 on 2024-11-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_trackbill_tbljournalentry_entry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountledger',
            name='idcredit',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
