# Generated by Django 4.0.6 on 2024-11-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_accountledger_idcredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountledger',
            name='ledger_name',
            field=models.CharField(max_length=200),
        ),
    ]
