# Generated by Django 4.0.6 on 2024-12-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_accountledger_ledger_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
