# Generated by Django 4.0.6 on 2024-12-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_expense_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumulativeledger',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
