# Generated by Django 4.0.6 on 2025-02-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_cumulativeledger_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbljournalentry',
            name='purchase',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
